version: '3.1'

services:

  mysql:
    container_name: mysql
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
